#!/bin/bash

# ============================================
# COMANDOS ÚTILES PARA EL PROYECTO PRODUKTUAK
# ============================================

echo "==================================="
echo "Produktuak - Comandos de desarrollo"
echo "==================================="
echo ""

# Configuración inicial
echo "1. INSTALACIÓN INICIAL"
echo "----------------------"
echo "composer install"
echo "cp .env.example .env"
echo "php artisan key:generate"
echo "php artisan migrate"
echo ""

# Comandos de desarrollo
echo "2. DESARROLLO"
echo "-------------"
echo "# Iniciar servidor:"
echo "php artisan serve"
echo ""
echo "# En otra terminal, si usas Vite:"
echo "npm run dev"
echo ""

# Comandos de base de datos
echo "3. BASE DE DATOS"
echo "----------------"
echo "# Ejecutar migraciones:"
echo "php artisan migrate"
echo ""
echo "# Revertir última migración:"
echo "php artisan migrate:rollback"
echo ""
echo "# Resetear y ejecutar todas las migraciones:"
echo "php artisan migrate:fresh"
echo ""
echo "# Ver estado de migraciones:"
echo "php artisan migrate:status"
echo ""

# Comandos útiles de Artisan
echo "4. ARTISAN (comandos útiles)"
echo "----------------------------"
echo "# Limpiar caché:"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo ""
echo "# Ver rutas:"
echo "php artisan route:list"
echo ""
echo "# Ver rutas de produktuak:"
echo "php artisan route:list --name=produktuak"
echo ""
echo "# Abrir tinker (consola interactiva):"
echo "php artisan tinker"
echo ""

# Comandos de tinker
echo "5. TINKER (ejemplos)"
echo "--------------------"
echo "# Crear producto:"
echo "App\\Models\\Produktu::create(['izena' => 'Test', 'deskribapena' => 'Prueba', 'prezioa' => 9.99]);"
echo ""
echo "# Listar todos los productos:"
echo "App\\Models\\Produktu::all();"
echo ""
echo "# Contar productos:"
echo "App\\Models\\Produktu::count();"
echo ""
echo "# Buscar producto por ID:"
echo "App\\Models\\Produktu::find(1);"
echo ""
echo "# Eliminar todos los productos:"
echo "App\\Models\\Produktu::truncate();"
echo ""

# Testing con curl
echo "6. TESTING API (con curl)"
echo "-------------------------"
echo "# Listar productos:"
echo "curl http://localhost:8000/api/produktuak"
echo ""
echo "# Crear producto:"
echo "curl -X POST http://localhost:8000/api/produktuak \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"izena\":\"Producto Test\",\"deskribapena\":\"Descripción\",\"prezioa\":19.99}'"
echo ""
echo "# Ver producto (ID 1):"
echo "curl http://localhost:8000/api/produktuak/1"
echo ""
echo "# Actualizar producto (ID 1):"
echo "curl -X PUT http://localhost:8000/api/produktuak/1 \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"izena\":\"Producto Actualizado\",\"deskribapena\":\"Nueva descripción\",\"prezioa\":29.99}'"
echo ""
echo "# Eliminar producto (ID 1):"
echo "curl -X DELETE http://localhost:8000/api/produktuak/1"
echo ""

# Comandos de MySQL
echo "7. MYSQL (comandos útiles)"
echo "--------------------------"
echo "# Conectar a MySQL:"
echo "mysql -u tu_usuario -p"
echo ""
echo "# Usar la base de datos:"
echo "USE produktuak;"
echo ""
echo "# Ver tablas:"
echo "SHOW TABLES;"
echo ""
echo "# Ver estructura de tabla:"
echo "DESCRIBE produktuak;"
echo ""
echo "# Ver productos:"
echo "SELECT * FROM produktuak;"
echo ""
echo "# Contar productos:"
echo "SELECT COUNT(*) FROM produktuak;"
echo ""
echo "# Vaciar tabla:"
echo "TRUNCATE TABLE produktuak;"
echo ""

# Troubleshooting
echo "8. TROUBLESHOOTING"
echo "------------------"
echo "# Si hay problemas con permisos:"
echo "chmod -R 775 storage bootstrap/cache"
echo ""
echo "# Si hay problemas con la base de datos:"
echo "php artisan migrate:fresh"
echo ""
echo "# Si hay problemas con el autoload:"
echo "composer dump-autoload"
echo ""
echo "# Ver logs de errores:"
echo "tail -f storage/logs/laravel.log"
echo ""

echo "==================================="
echo "Para más información, visita:"
echo "https://laravel.com/docs"
echo "==================================="
